import { StyleSheet } from 'react-native';
import { FULL_SCREEN_SAFE_TOP, DIALOG_SAFE_TOP, DIALOG_SAFE_BOTTOM } from '../../../constants/layout';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  topHeader: {
    alignItems: 'center',
    paddingTop: FULL_SCREEN_SAFE_TOP,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  dragHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#383B46',
    marginBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    flex: 1,
  },
  closeCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },
  toast: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 14,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
  },
  overviewStatsCard: {
    borderRadius: 20,
    borderWidth: 1.2,
    padding: 16,
    marginBottom: 20,
  },
  overviewTopRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 14,
  },
  overviewIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  overviewTextCol: {
    flex: 1,
    alignItems: 'flex-end',
  },
  overviewTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
    textAlign: 'right',
  },
  overviewSub: {
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'right',
  },
  overviewPillsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    paddingTop: 12,
  },
  overviewPill: {
    alignItems: 'center',
    flex: 1,
  },
  overviewPillNum: {
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 2,
  },
  overviewPillLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
  overviewDivider: {
    width: 1,
    height: 24,
  },
  groupHeaderTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'right',
    paddingHorizontal: 4,
  },
  groupCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderTopWidth: 1.2,
    overflow: 'hidden',
    marginBottom: 24,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  menuValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  subValueText: {
    fontSize: 12,
    fontWeight: '600',
  },
  themePillLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  menuItemText: {
    flex: 1,
    marginHorizontal: 12,
    fontSize: 15,
    fontWeight: '700',
  },
  menuIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBox: {
    marginVertical: 20,
    alignItems: 'center',
  },
  dataModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: DIALOG_SAFE_TOP,
    paddingBottom: DIALOG_SAFE_BOTTOM,
    paddingHorizontal: 20,
  },
  dataModalCard: {
    width: '100%',
    borderRadius: 24,
    borderWidth: 1.5,
    padding: 20,
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 14,
  },
  dataModalHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dataModalTitle: {
    fontSize: 17,
    fontWeight: '800',
  },
  modalExplanationText: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'right',
    marginBottom: 16,
  },
  settingControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(150, 150, 150, 0.2)',
  },
  segmentChoice: {
    flexDirection: 'row',
    backgroundColor: '#1E212B',
    borderRadius: 8,
    padding: 3,
    gap: 4,
  },
  segmentBtnHalf: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  segmentBtnHalfText: {
    fontSize: 12,
    fontWeight: '700',
  },
  controlLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  controlSub: {
    fontSize: 11,
    textAlign: 'right',
  },
  fieldSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 14,
    marginBottom: 8,
  },
  timePresetsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  timePresetBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timePresetText: {
    fontSize: 11,
    fontWeight: '700',
  },
  customMsgInput: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    fontSize: 13,
    textAlign: 'right',
  },
  testNotifyBtn: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  themeOptionCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    marginBottom: 10,
  },
  themeOptionInfo: {
    alignItems: 'flex-end',
    flex: 1,
    gap: 2,
  },
  languagesRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  langChoiceRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
  },
  langChoiceText: {
    fontSize: 14,
    fontWeight: '700',
  },
  emptyArchiveBox: {
    alignItems: 'center',
    paddingVertical: 24,
    gap: 8,
  },
  emptyArchiveTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  emptyArchiveSub: {
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 20,
  },
  archivedHabitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
  },
  archivedActions: {
    flexDirection: 'row',
  },
  archiveActionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  archivedHabitInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  archivedHabitName: {
    fontSize: 14,
    fontWeight: '700',
  },
  archivedHabitDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
  },
  sortOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
  },
  sortOptionLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  sortOptionDesc: {
    fontSize: 11,
  },
  introSlideContent: {
    alignItems: 'center',
    paddingVertical: 14,
    gap: 12,
  },
  introIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  introSlideTitle: {
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  introSlideDesc: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 16,
  },
  introDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginVertical: 12,
  },
  introDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  introBtnRow: {
    flexDirection: 'row',
    gap: 10,
  },
  whatsNewItem: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 0.5,
  },
  whatsNewItemTitle: {
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 2,
    textAlign: 'right',
  },
  whatsNewItemDesc: {
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'right',
  },
  starsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginVertical: 10,
  },
  feedbackTypeRow: {
    flexDirection: 'row',
    gap: 6,
    marginVertical: 10,
  },
  feedbackTypeBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackTypeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  feedbackTextInput: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 13,
    textAlign: 'right',
    textAlignVertical: 'top',
    height: 80,
  },
  dataActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 10,
  },
  dataActionTitle: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  dataActionSub: {
    fontSize: 11,
  },
  confirmBtn: {
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  ratingStarsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginVertical: 10,
  },
  feedbackCatChip: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
