import { StyleSheet } from 'react-native';

export const roadmapStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  viewModeSwitcherBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  viewModePillsRow: {
    gap: 8,
  },
  modeTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
  },
  modeTabText: {
    fontSize: 12,
    fontWeight: '800',
  },
  topSummaryBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  todayKpiCard: {
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
  },
  kpiRow: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  kpiTitle: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  kpiSubtitle: {
    fontSize: 11,
    fontWeight: '500',
  },
  kpiPercentBadge: {
    backgroundColor: '#FF6565',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  kpiPercentText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  progressBarTrack: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  timelineScroll: {
    flex: 1,
  },
  questTrailContent: {
    padding: 16,
    paddingBottom: 40,
  },
  questTrailIntro: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 20,
  },
  questTrailIntroText: {
    flex: 1,
    fontSize: 11.5,
    lineHeight: 17,
    fontWeight: '600',
  },
  trailPathContainer: {
    position: 'relative',
  },
  trailStationWrapper: {
    position: 'relative',
    marginBottom: 24,
  },
  trailDashedLine: {
    position: 'absolute',
    top: 50,
    bottom: -24,
    right: 23,
    width: 2,
    borderLeftWidth: 2,
    zIndex: 1,
  },
  trailNodeAndCardRow: {
    alignItems: 'flex-start',
    gap: 12,
    zIndex: 2,
  },
  nodeSealContainer: {
    alignItems: 'center',
    width: 48,
  },
  nodeSealCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  nodeDayNumber: {
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
  },
  nodeDayNameShort: {
    fontSize: 10,
    fontWeight: '700',
    marginTop: -1,
  },
  scratchThroughSeal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scratchLineDiagonal: {
    position: 'absolute',
    width: 40,
    height: 2.5,
    borderRadius: 2,
    transform: [{ rotate: '-35deg' }],
  },
  scratchLineCross: {
    position: 'absolute',
    width: 32,
    height: 2,
    borderRadius: 2,
    transform: [{ rotate: '35deg' }],
  },
  sealStatusTag: {
    marginTop: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  sealStatusTagText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '900',
  },
  trailStationCard: {
    flex: 1,
    borderRadius: 18,
    padding: 14,
  },
  trailCardHeader: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  trailDateTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  trailTaskCountSub: {
    fontSize: 11,
    fontWeight: '500',
    marginTop: 1,
  },
  todayGlowPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255, 101, 101, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  todayGlowText: {
    color: '#FF6565',
    fontSize: 11,
    fontWeight: '800',
  },
  stationTasksList: {
    gap: 8,
  },
  habitBranchGroup: {
    gap: 5,
  },
  habitBranchLabelRow: {
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  miniDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  habitBranchLabel: {
    fontSize: 11,
    fontWeight: '800',
  },
  trailTaskRow: {
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderRadius: 10,
    borderWidth: 1,
    gap: 8,
  },
  trailCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailTaskName: {
    flex: 1,
    fontSize: 12.5,
    fontWeight: '600',
  },
  trailDurationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  trailDurationText: {
    fontSize: 10,
    fontWeight: '700',
  },
  kanbanScroll: {
    flex: 1,
  },
  kanbanContent: {
    padding: 16,
    gap: 14,
  },
  kanbanColumnCard: {
    width: 270,
    borderRadius: 20,
    padding: 14,
  },
  kanbanColHeader: {
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  kanbanColBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  kanbanColTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  kanbanColDate: {
    fontSize: 11,
    fontWeight: '500',
    marginTop: 1,
  },
  kanbanTasksScroll: {
    maxHeight: 480,
  },
  kanbanHabitBlock: {
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    marginBottom: 10,
  },
  kanbanHabitRow: {
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  kanbanHabitTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  kanbanSubTasksList: {
    gap: 5,
  },
  kanbanTaskChip: {
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
  },
  kanbanTaskChipText: {
    flex: 1,
    fontSize: 11.5,
    fontWeight: '600',
  },
  kanbanTaskChipDuration: {
    fontSize: 10,
    fontWeight: '700',
  },
  kanbanQuickCheckBtn: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 4,
  },
  kanbanQuickCheckText: {
    fontSize: 11,
    fontWeight: '700',
  },
  timelineContent: {
    padding: 16,
    paddingBottom: 40,
    gap: 16,
  },
  dayCard: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
  },
  dayCardHeader: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  dayBadgeGroup: {
    alignItems: 'center',
    gap: 12,
  },
  dayCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCircleNum: {
    fontSize: 15,
    fontWeight: '900',
  },
  dayNameText: {
    fontSize: 16,
    fontWeight: '800',
  },
  todayPill: {
    backgroundColor: 'rgba(255, 101, 101, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  todayPillText: {
    color: '#FF6565',
    fontSize: 11,
    fontWeight: '800',
  },
  dayDateText: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
  },
  dayCompletionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
  },
  dayCompletionText: {
    fontSize: 12,
    fontWeight: '700',
  },
  habitsListContainer: {
    gap: 12,
  },
  habitSectionCard: {
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
  },
  habitSectionHeader: {
    alignItems: 'center',
    gap: 10,
  },
  habitIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  habitSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  singleHabitCheckBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subtasksList: {
    marginTop: 10,
    gap: 6,
  },
  subTaskRow: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    gap: 10,
  },
  subTaskCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subTaskTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
  },
  durationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
  },
  durationBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  quickAddSubTaskWrapper: {
    marginTop: 8,
  },
  addSubTaskTriggerBtn: {
    alignItems: 'center',
    gap: 5,
    paddingVertical: 4,
  },
  addSubTaskTriggerText: {
    fontSize: 12,
    fontWeight: '600',
  },
  inlineAddForm: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 4,
  },
  inlineInput: {
    fontSize: 13,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    marginBottom: 8,
  },
  fieldLabelSmall: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
  },
  daysChipsRow: {
    gap: 4,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  dayMiniChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
  },
  dayMiniChipText: {
    fontSize: 10,
    fontWeight: '700',
  },
  minutesRow: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  minutesInput: {
    width: 60,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 1,
    textAlign: 'center',
    fontSize: 12,
  },
  formButtonsRow: {
    gap: 8,
    justifyContent: 'flex-end',
  },
  saveSubTaskBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  saveSubTaskBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  cancelSubTaskBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
  },
  cancelSubTaskBtnText: {
    fontSize: 12,
    fontWeight: '600',
  },
  restDayNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    marginVertical: 4,
  },
  restDayNoticeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  emptyKanbanState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
    gap: 8,
  },
  emptyKanbanText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
});
